-- Default appearance for new characters
Config.Default = {
	['illenium-appearance'] = {
		['m'] = {
			tattoos = {
			},
			props = {
			[1] = {
				prop_id = 0,
				texture = -1,
				drawable = -1,
				},
			[2] = {
				prop_id = 1,
				texture = -1,
				drawable = -1,
				},
			[3] = {
				prop_id = 2,
				texture = -1,
				drawable = -1,
				},
			[4] = {
				prop_id = 6,
				texture = -1,
				drawable = -1,
				},
			[5] = {
				prop_id = 7,
				texture = -1,
				drawable = -1,
				},
			},
			model = "mp_m_freemode_01",
			headOverlays = {
			moleAndFreckles = {
				opacity = 0.5,
				color = 0,
				style = 0,
				},
			ageing = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			complexion = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			chestHair = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			beard = {
				opacity = 0,
				color = 20,
				style = 0,
				},
			eyebrows = {
				opacity = 1,
				color = 54,
				style = 30,
				},
			makeUp = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			bodyBlemishes = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			blemishes = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			lipstick = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			blush = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			sunDamage = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			},
			faceFeatures = {
			nosePeakHigh = -0.3,
			eyeBrownHigh = 0,
			noseBoneTwist = -0.3,
			cheeksBoneHigh = -0.2,
			jawBoneWidth = 0.5,
			eyeBrownForward = 0,
			cheeksWidth = 0.5,
			chinHole = 1,
			noseBoneHigh = 0.1,
			nosePeakLowering = 0.1,
			cheeksBoneWidth = -1,
			noseWidth = -0.7,
			neckThickness = 1,
			nosePeakSize = -0.1,
			eyesOpening = 0.8,
			chinBoneSize = 0,
			lipsThickness = 0,
			jawBoneBackSize = -0.6,
			chinBoneLowering = 0,
			chinBoneLenght = 0,
			},
			components = {
			[1] = {
				texture = 0,
				component_id = 0,
				drawable = 0,
				},
			[2] = {
				texture = 0,
				component_id = 1,
				drawable = 0,
				},
			[3] = {
				texture = 0,
				component_id = 2,
				drawable = 64,
				},
			[4] = {
				texture = 0,
				component_id = 3,
				drawable = 12,
				},
			[5] = {
				texture = 0,
				component_id = 4,
				drawable = 1,
				},
			[6] = {
				texture = 0,
				component_id = 5,
				drawable = 0,
				},
			[7] = {
				texture = 0,
				component_id = 6,
				drawable = 157,
				},
			[8] = {
				texture = 0,
				component_id = 7,
				drawable = 0,
				},
			[9] = {
				texture = 3,
				component_id = 8,
				drawable = 88,
				},
			[10] = {
				texture = 0,
				component_id = 9,
				drawable = 0,
				},
			[11] = {
				texture = 0,
				component_id = 10,
				drawable = 0,
				},
			[12] = {
				texture = 0,
				component_id = 11,
				drawable = 0,
				},
			},
			hair = {
			color = 20,
			highlight = 20,
			style = 64,
			},
			headBlend = {
			shapeFirst = 45,
			skinSecond = 0,
			shapeSecond = 45,
			skinMix = 0,
			skinFirst = 7,
			shapeMix = 0.4,
			},
			eyeColor = 24,
		},
		['f'] = {
			props = {
			[1] = {
				texture = -1,
				drawable = -1,
				prop_id = 0,
				},
			[2] = {
				texture = -1,
				drawable = -1,
				prop_id = 1,
				},
			[3] = {
				texture = -1,
				drawable = -1,
				prop_id = 2,
				},
			[4] = {
				texture = -1,
				drawable = -1,
				prop_id = 6,
				},
			[5] = {
				texture = -1,
				drawable = -1,
				prop_id = 7,
				},
			},
			headBlend = {
			skinSecond = 6,
			skinMix = 0.6,
			shapeFirst = 33,
			shapeMix = 0.6,
			shapeSecond = 6,
			skinFirst = 33,
			},
			model = "mp_f_freemode_01",
			eyeColor = 8,
			faceFeatures = {
			nosePeakHigh = 0.4,
			chinBoneSize = 0,
			eyeBrownHigh = -0.5,
			noseBoneHigh = 0,
			jawBoneBackSize = 0,
			chinBoneLowering = -1,
			cheeksWidth = 0,
			neckThickness = -0.5,
			jawBoneWidth = 0,
			cheeksBoneWidth = 0,
			noseWidth = -1,
			nosePeakSize = 0.5,
			eyesOpening = -0.6,
			noseBoneTwist = 0,
			lipsThickness = 0,
			chinHole = 0,
			cheeksBoneHigh = 0,
			nosePeakLowering = 0,
			eyeBrownForward = -0.8,
			chinBoneLenght = 1,
			},
			components = {
			[1] = {
				texture = 0,
				component_id = 0,
				drawable = 0,
				},
			[2] = {
				texture = 0,
				component_id = 1,
				drawable = 0,
				},
			[3] = {
				texture = 3,
				component_id = 2,
				drawable = 3,
				},
			[4] = {
				texture = 0,
				component_id = 3,
				drawable = 3,
				},
			[5] = {
				texture = 2,
				component_id = 4,
				drawable = 8,
				},
			[6] = {
				texture = 0,
				component_id = 5,
				drawable = 0,
				},
			[7] = {
				texture = 3,
				component_id = 6,
				drawable = 19,
				},
			[8] = {
				texture = 0,
				component_id = 7,
				drawable = 85,
				},
			[9] = {
				texture = 5,
				component_id = 8,
				drawable = 111,
				},
			[10] = {
				texture = 0,
				component_id = 9,
				drawable = 0,
				},
			[11] = {
				texture = 0,
				component_id = 10,
				drawable = 0,
				},
			[12] = {
				texture = 2,
				component_id = 11,
				drawable = 25,
				},
			},
			hair = {
			style = 3,
			color = 34,
			highlight = 38,
			},
			headOverlays = {
			makeUp = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			blush = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			bodyBlemishes = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			lipstick = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			sunDamage = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			moleAndFreckles = {
				opacity = 0.8,
				color = 0,
				style = 12,
				},
			blemishes = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			eyebrows = {
				opacity = 0.7,
				color = 52,
				style = 32,
				},
			complexion = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			ageing = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			beard = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			chestHair = {
				opacity = 0,
				color = 0,
				style = 0,
				},
			},
			tattoos = {
			},
		}  
	},
	['skinchanger'] = {
		["m"] = {
			mom = 43,
			dad = 29,
			face_md_weight = 61,
			skin_md_weight = 27,
			nose_1 = -5,
			nose_2 = 6,
			nose_3 = 5,
			nose_4 = 8,
			nose_5 = 10,
			nose_6 = 0,
			cheeks_1 = 2,
			cheeks_2 = -10,
			cheeks_3 = 6,
			lip_thickness = -2,
			jaw_1 = 0,
			jaw_2 = 0,
			chin_1 = 0,
			chin_2 = 0,
			chin_13 = 0,
			chin_4 = 0,
			neck_thickness = 0,
			hair_1 = 76,
			hair_2 = 0,
			hair_color_1 = 61,
			hair_color_2 = 29,
			tshirt_1 = 4,
			tshirt_2 = 2,
			torso_1 = 23,
			torso_2 = 2,
			decals_1 = 0,
			decals_2 = 0,
			arms = 1,
			arms_2 = 0,
			pants_1 = 28,
			pants_2 = 3,
			shoes_1 = 70,
			shoes_2 = 2,
			mask_1 = 0,
			mask_2 = 0,
			bproof_1 = 0,
			bproof_2 = 0,
			chain_1 = 22,
			chain_2 = 2,
			helmet_1 = -1,
			helmet_2 = 0,
			glasses_1 = 0,
			glasses_2 = 0,
			watches_1 = -1,
			watches_2 = 0,
			bracelets_1 = -1,
			bracelets_2 = 0,
			bags_1 = 0,
			bags_2 = 0,
			eye_color = 0,
			eye_squint = 0,
			eyebrows_2 = 0,
			eyebrows_1 = 0,
			eyebrows_3 = 0,
			eyebrows_4 = 0,
			eyebrows_5 = 0,
			eyebrows_6 = 0,
			makeup_1 = 0,
			makeup_2 = 0,
			makeup_3 = 0,
			makeup_4 = 0,
			lipstick_1 = 0,
			lipstick_2 = 0,
			lipstick_3 = 0,
			lipstick_4 = 0,
			ears_1 = -1,
			ears_2 = 0,
			chest_1 = 0,
			chest_2 = 0,
			chest_3 = 0,
			bodyb_1 = -1,
			bodyb_2 = 0,
			bodyb_3 = -1,
			bodyb_4 = 0,
			age_1 = 0,
			age_2 = 0,
			blemishes_1 = 0,
			blemishes_2 = 0,
			blush_1 = 0,
			blush_2 = 0,
			blush_3 = 0,
			complexion_1 = 0,
			complexion_2 = 0,
			sun_1 = 0,
			sun_2 = 0,
			moles_1 = 0,
			moles_2 = 0,
			beard_1 = 11,
			beard_2 = 10,
			beard_3 = 0,
			beard_4 = 0
		},
		["f"] = {
			mom = 28,
			dad = 6,
			face_md_weight = 63,
			skin_md_weight = 60,
			nose_1 = -10,
			nose_2 = 4,
			nose_3 = 5,
			nose_4 = 0,
			nose_5 = 0,
			nose_6 = 0,
			cheeks_1 = 0,
			cheeks_2 = 0,
			cheeks_3 = 0,
			lip_thickness = 0,
			jaw_1 = 0,
			jaw_2 = 0,
			chin_1 = -10,
			chin_2 = 10,
			chin_13 = -10,
			chin_4 = 0,
			neck_thickness = -5,
			hair_1 = 43,
			hair_2 = 0,
			hair_color_1 = 29,
			hair_color_2 = 35,
			tshirt_1 = 111,
			tshirt_2 = 5,
			torso_1 = 25,
			torso_2 = 2,
			decals_1 = 0,
			decals_2 = 0,
			arms = 3,
			arms_2 = 0,
			pants_1 = 12,
			pants_2 = 2,
			shoes_1 = 20,
			shoes_2 = 10,
			mask_1 = 0,
			mask_2 = 0,
			bproof_1 = 0,
			bproof_2 = 0,
			chain_1 = 85,
			chain_2 = 0,
			helmet_1 = -1,
			helmet_2 = 0,
			glasses_1 = 33,
			glasses_2 = 12,
			watches_1 = -1,
			watches_2 = 0,
			bracelets_1 = -1,
			bracelets_2 = 0,
			bags_1 = 0,
			bags_2 = 0,
			eye_color = 8,
			eye_squint = -6,
			eyebrows_2 = 7,
			eyebrows_1 = 32,
			eyebrows_3 = 52,
			eyebrows_4 = 9,
			eyebrows_5 = -5,
			eyebrows_6 = -8,
			makeup_1 = 0,
			makeup_2 = 0,
			makeup_3 = 0,
			makeup_4 = 0,
			lipstick_1 = 0,
			lipstick_2 = 0,
			lipstick_3 = 0,
			lipstick_4 = 0,
			ears_1 = -1,
			ears_2 = 0,
			chest_1 = 0,
			chest_2 = 0,
			chest_3 = 0,
			bodyb_1 = -1,
			bodyb_2 = 0,
			bodyb_3 = -1,
			bodyb_4 = 0,
			age_1 = 0,
			age_2 = 0,
			blemishes_1 = 0,
			blemishes_2 = 0,
			blush_1 = 0,
			blush_2 = 0,
			blush_3 = 0,
			complexion_1 = 0,
			complexion_2 = 0,
			sun_1 = 0,
			sun_2 = 0,
			moles_1 = 12,
			moles_2 = 8,
			beard_1 = 0,
			beard_2 = 0,
			beard_3 = 0,
			beard_4 = 0
		}
	},


	-- fivemappearance
	['fivem-appearance'] = {
		['m'] = {
			props = {
			[1] = {
				texture = -1,
				drawable = -1,
				prop_id = 0,
				},
			[2] = {
				texture = 0,
				drawable = 0,
				prop_id = 1,
				},
			[3] = {
				texture = -1,
				drawable = -1,
				prop_id = 2,
				},
			[4] = {
				texture = -1,
				drawable = -1,
				prop_id = 6,
				},
			[5] = {
				texture = -1,
				drawable = -1,
				prop_id = 7,
				},
			},
			headBlend = {
			skinSecond = 0,
			skinMix = 0.3,
			shapeFirst = 21,
			shapeMix = 0.4,
			shapeSecond = 0,
			skinFirst = 21,
			},
			model = "mp_m_freemode_01",
			eyeColor = 0,
			faceFeatures = {
			jawBoneWidth = -0.2,
			noseBoneTwist = -0.3,
			eyeBrownHigh = 0,
			noseBoneHigh = 0.1,
			jawBoneBackSize = -0.2,
			chinBoneLowering = 0,
			eyeBrownForward = 0,
			neckThickness = 0,
			nosePeakHigh = 0,
			nosePeakLowering = 0.1,
			lipsThickness = -0.4,
			nosePeakSize = -0.1,
			chinHole = 0,
			cheeksWidth = 0.5,
			chinBoneSize = 0,
			eyesOpening = 0,
			cheeksBoneHigh = -0.2,
			noseWidth = -0.5,
			cheeksBoneWidth = -1,
			chinBoneLenght = 0,
			},
			components = {
			[1] = {
				texture = 0,
				component_id = 0,
				drawable = 0,
				},
			[2] = {
				texture = 0,
				component_id = 1,
				drawable = 0,
				},
			[3] = {
				texture = 0,
				component_id = 2,
				drawable = 49,
				},
			[4] = {
				texture = 0,
				component_id = 3,
				drawable = 1,
				},
			[5] = {
				texture = 0,
				component_id = 4,
				drawable = 25,
				},
			[6] = {
				texture = 0,
				component_id = 5,
				drawable = 0,
				},
			[7] = {
				texture = 2,
				component_id = 6,
				drawable = 69,
				},
			[8] = {
				texture = 2,
				component_id = 7,
				drawable = 22,
				},
			[9] = {
				texture = 0,
				component_id = 8,
				drawable = 4,
				},
			[10] = {
				texture = 0,
				component_id = 9,
				drawable = 0,
				},
			[11] = {
				texture = 0,
				component_id = 10,
				drawable = 0,
				},
			[12] = {
				texture = 0,
				component_id = 11,
				drawable = 10,
				},
			},
			hair = {
			style = 49,
			color = 47,
			highlight = 29,
			},
			headOverlays = {
			makeUp = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			chestHair = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			bodyBlemishes = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			lipstick = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			sunDamage = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			moleAndFreckles = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			blemishes = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			blush = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			complexion = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			eyebrows = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			beard = {
				style = 11,
				color = 0,
				opacity = 1,
				},
			ageing = {
				style = 0,
				color = 0,
				opacity = 0,
				},
			},
			tattoos = {
			},
		},
		['f'] = {
			props = {
			   [1] = {
				  texture = -1,
				  drawable = -1,
				  prop_id = 0,
				},
			   [2] = {
				  texture = -1,
				  drawable = -1,
				  prop_id = 1,
				},
			   [3] = {
				  texture = -1,
				  drawable = -1,
				  prop_id = 2,
				},
			   [4] = {
				  texture = -1,
				  drawable = -1,
				  prop_id = 6,
				},
			   [5] = {
				  texture = -1,
				  drawable = -1,
				  prop_id = 7,
				},
			 },
			headBlend = {
			   skinSecond = 6,
			   skinMix = 0.6,
			   shapeFirst = 33,
			   shapeMix = 0.6,
			   shapeSecond = 6,
			   skinFirst = 33,
			 },
			model = "mp_f_freemode_01",
			eyeColor = 8,
			faceFeatures = {
			   nosePeakHigh = 0.4,
			   chinBoneSize = 0,
			   eyeBrownHigh = -0.5,
			   noseBoneHigh = 0,
			   jawBoneBackSize = 0,
			   chinBoneLowering = -1,
			   cheeksWidth = 0,
			   neckThickness = -0.5,
			   jawBoneWidth = 0,
			   cheeksBoneWidth = 0,
			   noseWidth = -1,
			   nosePeakSize = 0.5,
			   eyesOpening = -0.6,
			   noseBoneTwist = 0,
			   lipsThickness = 0,
			   chinHole = 0,
			   cheeksBoneHigh = 0,
			   nosePeakLowering = 0,
			   eyeBrownForward = -0.8,
			   chinBoneLenght = 1,
			 },
			components = {
			   [1] = {
				  texture = 0,
				  component_id = 0,
				  drawable = 0,
				},
			   [2] = {
				  texture = 0,
				  component_id = 1,
				  drawable = 0,
				},
			   [3] = {
				  texture = 3,
				  component_id = 2,
				  drawable = 3,
				},
			   [4] = {
				  texture = 0,
				  component_id = 3,
				  drawable = 3,
				},
			   [5] = {
				  texture = 2,
				  component_id = 4,
				  drawable = 8,
				},
			   [6] = {
				  texture = 0,
				  component_id = 5,
				  drawable = 0,
				},
			   [7] = {
				  texture = 3,
				  component_id = 6,
				  drawable = 19,
				},
			   [8] = {
				  texture = 0,
				  component_id = 7,
				  drawable = 85,
				},
			   [9] = {
				  texture = 5,
				  component_id = 8,
				  drawable = 111,
				},
			   [10] = {
				  texture = 0,
				  component_id = 9,
				  drawable = 0,
				},
			   [11] = {
				  texture = 0,
				  component_id = 10,
				  drawable = 0,
				},
			   [12] = {
				  texture = 2,
				  component_id = 11,
				  drawable = 25,
				},
			 },
			hair = {
			   style = 3,
			   color = 34,
			   highlight = 38,
			 },
			headOverlays = {
			   makeUp = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   blush = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   bodyBlemishes = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   lipstick = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   sunDamage = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   moleAndFreckles = {
				  opacity = 0.8,
				  color = 0,
				  style = 12,
				},
			   blemishes = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   eyebrows = {
				  opacity = 0.7,
				  color = 52,
				  style = 32,
				},
			   complexion = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   ageing = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   beard = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			   chestHair = {
				  opacity = 0,
				  color = 0,
				  style = 0,
				},
			 },
			tattoos = {
			 },
		}  
	},
	['qb-clothing'] = {
		['m'] = {
			nose_0 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 4,
			 },
			nose_3 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			shoes = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 1,
			   item = 24,
			 },
			chimp_bone_width = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			nose_4 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			lipstick = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = 3,
			 },
			eye_opening = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			face = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			eyebrown_high = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			cheek_3 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			bracelet = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = -1,
			 },
			lips_thickness = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			cheek_1 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			eyebrows = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = 4,
			 },
			facemix = {
			   shapeMix = 0,
			   defaultSkinMix = 0.0,
			   skinMix = 0.0,
			   defaultShapeMix = 0.0,
			 },
			beard = {
			   texture = 9,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = 7,
			 },
			chimp_bone_lowering = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			vest = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			chimp_hole = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			face2 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 3,
			 },
			ear = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = -1,
			 },
			ageing = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = 14,
			 },
			mask = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			makeup = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = -1,
			 },
			chimp_bone_lenght = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			cheek_2 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			glass = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			sex = 0,
			jaw_bone_width = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			nose_5 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			watch = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = -1,
			 },
			nose_2 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			decals = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			eye_color = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = 5,
			 },
			pants = {
			   texture = 4,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 27,
			 },
			bag = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			torso2 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 34,
			 },
			hair = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			arms = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			hat = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = -1,
			 },
			accessory = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			blush = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = -1,
			 },
			['t-shirt'] = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 1,
			   item = 1,
			 },
			neck_thikness = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			moles = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = 4,
			 },
			nose_1 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			jaw_bone_back_lenght = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			eyebrown_forward = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
		},
		['f'] = {
			vest = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			nose_3 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 2,
			 },
			shoes = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 1,
			   item = 10,
			 },
			chimp_bone_width = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			nose_4 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			torso2 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 14,
			 },
			eye_opening = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			face = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 21,
			 },
			eyebrown_high = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			jaw_bone_back_lenght = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			jaw_bone_width = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			lips_thickness = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			cheek_1 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			eyebrows = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = -1,
			 },
			facemix = {
			   shapeMix = 0.0,
			   defaultSkinMix = 0.0,
			   skinMix = 0.0,
			   defaultShapeMix = 0.0,
			 },
			nose_0 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 4,
			 },
			chimp_bone_lowering = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			lipstick = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = -1,
			 },
			chimp_hole = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			face2 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 5,
			 },
			ear = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = -1,
			 },
			ageing = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = 3,
			 },
			beard = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = -1,
			 },
			makeup = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = -1,
			 },
			chimp_bone_lenght = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			cheek_2 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			glass = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			sex = 1,
			mask = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			hat = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = -1,
			 },
			watch = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = -1,
			 },
			nose_2 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 4,
			 },
			nose_5 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			eye_color = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = 4,
			 },
			decals = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			pants = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 10,
			 },
			bracelet = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = -1,
			 },
			hair = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 11,
			 },
			arms = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			bag = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			accessory = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = -1,
			 },
			blush = {
			   texture = 1,
			   defaultTexture = 1,
			   defaultItem = -1,
			   item = -1,
			 },
			cheek_3 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			neck_thikness = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
			moles = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = -1,
			   item = 2,
			 },
			['t-shirt'] = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 1,
			   item = 15,
			 },
			nose_1 = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 4,
			 },
			eyebrown_forward = {
			   texture = 0,
			   defaultTexture = 0,
			   defaultItem = 0,
			   item = 0,
			 },
		}
	}
	  
}